# Generated by Django 2.2.2 on 2019-06-13 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0003_auto_20190613_0753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Planning',
        ),
    ]
