# Generated by Django 2.2.2 on 2019-06-13 08:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0004_auto_20190613_0813'),
    ]

    operations = []
