# Generated by Django 2.2.2 on 2019-06-13 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_auto_20190613_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='date',
        ),
        migrations.AlterField(
            model_name='planning',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
