# Generated by Django 2.2.2 on 2019-06-13 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_auto_20190613_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='time',
        ),
        migrations.AlterField(
            model_name='planning',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
    ]
