# Generated by Django 2.2.2 on 2019-06-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_auto_20190613_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='date',
        ),
    ]
