# Generated by Django 2.2.2 on 2019-06-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_remove_planning_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
