# Generated by Django 2.2.2 on 2019-06-13 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'verbose_name': 'rendez vous'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='auteur',
            new_name='hour',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='titre',
            new_name='instructor',
        ),
        migrations.RemoveField(
            model_name='article',
            name='contenu',
        ),
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
    ]
