# Generated by Django 2.2.2 on 2019-06-13 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0020_auto_20190613_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='article',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_Student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
