# Generated by Django 2.2.2 on 2019-06-13 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0023_auto_20190613_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Planning',
        ),
    ]
