# Generated by Django 2.2.2 on 2019-06-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0024_auto_20190613_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planning',
            options={},
        ),
    ]
