# Generated by Django 2.2.2 on 2019-06-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0027_auto_20190613_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planning',
            options={'ordering': ['date']},
        ),
    ]
