# Generated by Django 2.2.2 on 2019-06-14 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0029_auto_20190614_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
