# Generated by Django 2.2.2 on 2019-06-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0032_auto_20190614_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
