# Generated by Django 2.2.2 on 2019-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0035_forfait'),
    ]

    operations = [
        migrations.AddField(
            model_name='forfait',
            name='heur_payé',
            field=models.CharField(default='', max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forfait',
            name='total_heur',
            field=models.CharField(default=' ', max_length=42),
            preserve_default=False,
        ),
    ]
