# Generated by Django 2.2.2 on 2019-06-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0036_auto_20190614_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forfait',
            old_name='heur_payé',
            new_name='heur_payer',
        ),
    ]
